window.PROFILES = {
  "ben": {"id":"ben","name":"Ben","age":30,"wing":"male","brief":"Bisexual Black","nationality":"British","height":"6'1\" / 185 cm","body":"Athletic / Toned","city":"London — South London / easy to Central","photo":"photos/ben.jpg","about":"Tall, athletic, easy to talk to. Not performative. I like the room to feel normal before it gets sexual.","minDuration":"1 hour"},
  "glenn": {"id":"glenn","name":"Glenn","age":34,"wing":"male","brief":"Straight White","nationality":"British","height":"5'11\" / 180 cm","body":"Average / Natural","city":"London — Essex fringe / East London access","photo":"photos/glenn.jpg","about":"Ordinary, tidy, easy company. More boyfriend than performer.","minDuration":"1 hour"},
  "travis": {"id":"travis","name":"Travis","age":27,"wing":"male","brief":"Gay White","nationality":"British","height":"5'10\" / 178 cm","body":"Athletic / Toned","city":"London — Vauxhall / Zone 1–2","photo":"photos/travis.jpg","about":"Groomed, gym-fit, better in person than on a rushed photo. I like a guest who can laugh.","minDuration":"1 hour"},
  "luke": {"id":"luke","name":"Luke","age":31,"wing":"male","brief":"Bisexual White","nationality":"British","height":"6'0\" / 183 cm","body":"Muscular / Fit","city":"London — North / Camden side","photo":"photos/luke.jpg","about":"Taller, tattooed, easier than I look. I will not rush a nervous guest.","minDuration":"1 hour"},
  "jeremy": {"id":"jeremy","name":"Jeremy","age":36,"wing":"male","brief":"Straight White Posh","nationality":"British","height":"6'2\" / 188 cm","body":"Athletic / Toned","city":"London — Kensington / Chelsea / Mayfair circuit","photo":"photos/jeremy.jpg","about":"Tall, well dressed, good table manners. The point is that you can take me anywhere.","minDuration":"2 hours"},
  "andreia": {"id":"andreia","name":"Andreia","age":31,"wing":"female","brief":"Bisexual White BBW","nationality":"Portuguese","height":"5'5\" / 165 cm","body":"Voluptuous / Full-Figured","city":"London — Zone 2 West","photo":"photos/andreia.jpg","about":"Soft, smiley, Portuguese accent, very tactile. I look like a woman, not a filtered stick.","minDuration":"1 hour"},
  "tanita": {"id":"tanita","name":"Tanita","age":29,"wing":"female","brief":"Bisexual mixed race high standard","nationality":"British","height":"5'8\" / 173 cm","body":"Athletic / Toned","city":"London — Prime Central","photo":"photos/tanita.jpg","about":"Tall, mixed, very put together. I am better as a date than as a checklist.","minDuration":"2 hours"},
  "caroline": {"id":"caroline","name":"Caroline","age":32,"wing":"female","brief":"White cheap","nationality":"British","height":"5'4\" / 162 cm","body":"Average / Natural","city":"London — Zone 3","photo":"photos/caroline.jpg","about":"Normal, blonde, smiley. Not a photoshoot every hour.","minDuration":"1 hour"},
  "faye": {"id":"faye","name":"Faye","age":37,"wing":"female","brief":"Strict DOMINANT","nationality":"British","height":"5'9\" / 175 cm","body":"Athletic / Toned","city":"London — Zone 2","photo":"photos/faye.jpg","about":"Taller than you expect, calm, dressed in black. I do not giggle to make you comfortable.","minDuration":"1 hour"},
  "joselyn": {"id":"joselyn","name":"Joselyn","age":27,"wing":"female","brief":"sub white","nationality":"British","height":"5'3\" / 160 cm","body":"Slim / Petite","city":"London — Zone 2 North","photo":"photos/joselyn.jpg","about":"Petite, quiet at first, very present once I trust the room.","minDuration":"1 hour"},
  "alexis": {"id":"alexis","name":"Alexis","age":31,"wing":"transexual","brief":"Black","nationality":"British","height":"5'10\" / 178 cm","body":"Athletic / Toned","city":"London — East / Canary","photo":"photos/alexis.jpg","about":"Tall, dark, glam, woman in the room. Ask before you touch.","minDuration":"1 hour"},
  "marianna": {"id":"marianna","name":"Marianna","age":29,"wing":"transexual","brief":"Brazilian White big bum","nationality":"Brazilian","height":"5'6\" / 168 cm","body":"Curvy / Hourglass","city":"London — Zone 2 West","photo":"photos/marianna.jpg","about":"Brazilian, white-skin, obvious hips and bum, accent, playful.","minDuration":"1 hour"},
  "nicole": {"id":"nicole","name":"Nicole","age":28,"wing":"transexual","brief":"Philippines","nationality":"Filipino","height":"5'4\" / 163 cm","body":"Slim / Petite","city":"London — Zone 2 / 3 West","photo":"photos/nicole.jpg","about":"Petite, pretty, soft voice, Filipina. I warm up if you are kind.","minDuration":"1 hour"},
  "sophie": {"id":"sophie","name":"Sophie","age":31,"wing":"transexual","brief":"Thai","nationality":"Thai","height":"5'7\" / 170 cm","body":"Slim / Petite","city":"London — Zone 1/2 West","photo":"photos/sophie.jpg","about":"Tall-slim Thai, soft voice, good hands.","minDuration":"1 hour"},
  "duda": {"id":"duda","name":"Duda","age":28,"wing":"transexual","brief":"Brazilian stunning white","nationality":"Brazilian","height":"5'8\" / 173 cm","body":"Athletic / Toned","city":"London — Chelsea–Marylebone","photo":"photos/duda.jpg","about":"Tall, white-Brazilian, model face, long legs.","minDuration":"2 hours"}
};
